# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Zai Likh' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DropDown'
  pod 'Ono'
  pod 'SwiftDrawer'
  
  # Pods for Zai Likh

  target 'Zai LikhTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Zai LikhUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
